const express = require("express");
const { connectdatabase } = require("./connectiondb");
require("dotenv").config();
const app = express();
const PORT = process.env.PORT;
const MONGO_URL = process.env.MONGO_URL;
const cookieParser = require("cookie-parser");
const Staticrouter = require("./routes/Staticroutes");
connectdatabase(MONGO_URL);
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cookieParser());
app.use("/", Staticrouter);
app.listen(PORT, () => console.log(`Server is running on PORT ${PORT}`));
